### ISSUE TITLE
Support weights?

### ISSUE THREAD

**Issue by MaxGhenis** [oliviaguest/gini#2]
Would it be possible to adapt this to support a second `weights` array?

This page includes an R function that adds weights support: http://ellisp.github.io/blog/2017/08/05/weighted-gini

**Comment by oliviaguest** [comment]
I don't have time to look into this, but please feel free to try it out.

**Comment by MaxGhenis** [comment]
[Here's a solution](https://stackoverflow.com/a/48999797/1840471):

```
import numpy as np
import pandas as pd

def gini(x, w=None):
    # Array indexing requires reset indexes.
    x = pd.Series(x).reset_index(drop=True)
    if w is None:
        w = np.ones_like(x)
    w = pd.Series(w).reset_index(drop=True)
    n = x.size
    wxsum = sum(w * x)
    wsum = sum(w)
    sxw = np.argsort(x)
    sx = x[sxw] * w[sxw]
    sw = w[sxw]
    pxi = np.cumsum(sx) / wxsum
    pci = np.cumsum(sw) / wsum
    g = 0.0
    for i in np.arange(1, n):
        g = g + pxi[i] * pci[i - 1] - pci[i] * pxi[i - 1]
    return g
```

Pretty different structure from your current one so I won't edit it, but hope it's helpful to those who come across this.

**Comment by impredicative** [comment]
Weighted gini is very important and should be a part of any respectable gini package.

**Comment by oliviaguest** [comment]
@MaxGhenis solution seems useful for that.

**Comment by impredicative** [comment]
There are solutions [here](https://stackoverflow.com/questions/48981516/weighted-gini-coefficient-in-python) and [here](https://stackoverflow.com/questions/48999542/more-efficient-weighted-gini-coefficient-in-python/).

**Comment by oliviaguest** [comment]
Great. That question was asked by the other person in this thread. I wrote this before that question because there was nothing out there for my needs. Feel free to do a PR, if you want to.

**Comment by MaxGhenis** [comment]
I added a `gini()` function with weights to my `taxcalc_helpers` package [here](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/taxcalc_helpers/utils.py#L5). You can install with:

    pip install git+git://github.com/maxghenis/taxcalc_helpers.git

**Comment by impredicative** [comment]
@MaxGhenis Why `zero_negatives=True` by default? Why not `zero_negatives=False`? It's kind of dangerous for a function named `gini`, ain't it?

**Comment by MaxGhenis** [comment]
I'm not aware of a consensus approach for dealing with negative values, and zeroing them out is consistent with other practices in the `taxcalc` project of which that's a part.

**Comment by impredicative** [comment]
Okay. Economic indicators, etc. can definitely have valid negative values even if they don't have this for the purpose of taxes. I'm just afraid that someone will copy and paste your function without realizing what it's doing.

**Comment by MaxGhenis** [comment]
There are valid negative values of after-tax income (what I use this for), but they can be so negative that it affects aggregate metrics in difficult-to-interpret ways. If someone is passing negative values to a Gini function they should pay extra attention to begin with. But given a source that including negative values as-is is the standard, I'd gladly change the default behavior.

**Comment by MaxGhenis** [comment]
@oliviaguest's implementation [also zeroes out negatives](https://github.com/oliviaguest/gini/blob/master/gini.py#L11), though it does so by subtracting the minimum (i.e. adding its magnitude) to all values.

**Comment by mu578** [comment]
@hello, if you design a descent weighted  version you might immediately want to implement the skipping zero step, statistic indicators are still statistics + you should pass a policy regarding `your data transform` or some kind of callback mechanism; everybody knows that some kind of `normalization` can be destructive for some problems, that's always problematic to have functions enforcing a oneway policy on such topic.

**Comment by impredicative** [comment]
Naively handling negative values in one of many ways (skipping, shifting, zeroing, rescaling, etc.) can dramatically alter the analysis, resulting in a vastly different conclusion. It's saner for the gini function to never silently do any special processing. Any special processing of negative values, if necessary, should be done outside the gini function.

**Comment by MaxGhenis** [comment]
You swayed me, @impredicative. Given the multiple possible ways of dealing with negative values, I've changed the default behavior of my `gini` function to leave the values raw. I also added @oliviaguest's shifting method as an option for dealing with them. Here's an [example notebook](https://github.com/MaxGhenis/taxcalc_helpers/blob/master/examples/gini.ipynb) of the new behavior.
