### ISSUE TITLE
Handle negative values less dangerously

### ISSUE THREAD

**Issue by impredicative** [oliviaguest/gini#3]
Currently, the range is shifted to make values be non-negative:

```python
    if np.amin(array) < 0:
        # Values cannot be negative:
        array -= np.amin(array)
```

This is dangerous. This should be controlled by a user-specified function argument with a default value of False, e.g. `shift_negative=False`.

I know this is a documented assumption that the inputs be positive. At a minimum, it's safer to raise an exception if an assumption is violated, rather than to handle it forcibly.

**Comment by impredicative** [comment]
I don't expect anything to change, so I will close this issue.

**Comment by oliviaguest** [comment]
I'm happy to make this edit if you wanna set up a PR?
