### ISSUE TITLE
Doesn't return negative gini

### ISSUE THREAD

**Issue by acell** [oliviaguest/gini#8]
Hi, thank you for putting this together! In the readme, you have an example creating random integers and showing the gini is "low", being .33. As someone who has built many ML models with a gini under .33, this seemed weird to me. The other gini function you reference being similar to, here (https://github.com/pysal/pysal/pull/862/files), has a function that instead returns around -.33 as opposed to +.33 when calculating the gini of random numbers. Thus, I believe there is an issue returning negative ginis in your function.

**Comment by oliviaguest** [comment]
I suspect it's because this Gini function doesn't accept/allow negative numbers TBC as part of the definition, while the others do? Take a look here, as linked from the readme: https://www.statsdirect.com/help/default.htm#nonparametric_methods/gini.htm
